### ISSUE TITLE
Иконка вместо знака рубля

### ISSUE THREAD

**Issue by iamale** [theaqua/courses#1]
[`40 000 <i class="fa fa-rub"></i>`][line] &mdash; так и задумывалось?

![Рубли, рубли эвривэа](https://cloud.githubusercontent.com/assets/1298948/3292409/0e105c2a-f58f-11e3-82f4-a38b75cc7b73.png)

Я бы скорее использовал либо [специальный шрифт][font], либо вообще перешел на какой-нибудь PT Sans, в котором знак есть изначально (но это уже слишком радикально, наверное).

[line]: https://github.com/theaqua/courses/blob/master/app/index.html#L149
[font]: http://www.artlebedev.ru/kovodstvo/sections/159/#12

**Comment by iamale** [comment]
Так и не поправил ведь. :smirk:

**Comment by theaqua** [comment]
Ну конечно, сайт заброшен давно.
